name: belt
description: Utility Belt
version: 0.1.0
homepage: https://github.com/DirectMyFile/belt
authors:
- Kenneth Endfinger <kaendfinger@gmail.com>
dependencies:
  path: "^1.3.9"
environment:
  sdk: '>=1.10.0 <3.0.0'
